node:
  ros__parameters:
    # before1: "param.yaml"
    before2: "node-specific param.yaml"
    # after1: "param.yaml"
    after2: "node-specific param.yaml"

ns/node:
  ros__parameters:
    # before1: "param.yaml"
    before2: "node-specific param.yaml"
    # after1: "param.yaml"
    after2: "node-specific param.yaml"

/**:
  ros__parameters:
    before1: "wildcard param.yaml"
    # before2: "param.yaml"
    after1: "wildcard param.yaml"
    # after2: "param.yaml"
